Global:
  session_base_path: "./SESSIONS_Char"

Datasets:
  NLST:
    in_uids: "./utils_tmp/csvs/nlst_input.csv"
    in_dtype: ".dcm"
    description: "National Lung Screening Trial dataset"
  UCLA CECT:
    in_uids: "./utils_tmp/final_csvs_char/ucla_cect_subset.csv"
    in_dtype: ".dcm"
    description: "UCLA Contrast Enhanced dataset"

Modules:
  Characterization: false
  Harmonization: true
  Robustness: false

Characterization:
  input_datasets:
    - name: NLST
  metrics:
    voxel:
      - all
    metadata:
      - all
  params:
    clip_range : [-1024, 3071] # Standard HU range
    bins: 64
    kde_points: 1e3
    kde_sample: 1e5 # Sample voxel to compute kde; If removed, computes kde for all voxel values - can be computationally expensive

Harmonization:
  mode: "test"
  input_datasets:
    - name: NLST
      in_uids: "./utils_tmp/csvs/totest_order.csv"
  models:
    - name: SNGAN
      pretrained_G: "./pretrained_weights/SNGAN/latestG-1-1.pth"
  param:
    tile_xy: 512
    tile_z: 32
    z_overlap: 4
    gpu_id: 0
    out_dtype: ".nii.gz"
  metrics: # sobel, radiomic, snr
    - snr
    - sobel

Robustness:
  input_datasets:
    # - name: NLST
    #   variability:
    #     - manufacturer
    #   load_from: "20250214-220226-4f"
    #   in_uids: "./utils_tmp/csvs/nlst_input_subset.csv"

    - name: UCLA CECT
      variability:
        - convolution_kernel
      load_from: "20250214-220226-4f"
      in_uids: "./utils_tmp/final_csvs_char/ucla_cect_subset.csv"

  param:
    model_type: "sybil_ensemble"
    evaluate: true
