Global:
  session_base_path: "./SESSIONS_SYBIL"

Datasets:
  UCLA-LDCT:
    in_uids: "./utils_tmp/filtered_csv/ucla_ldct_harm_mnt.csv"
    in_dtype: ".dcm"
    description: "National Lung Screening Trial dataset"
  NLST-2:
    in_uids: "./utils_tmp/csvs/totest_order.csv"
    in_dtype: ".dcm"
    description: "National Lung Screening Trial dataset again"

Modules:
  Characterization: true
  Harmonization: false
  Robustness: false

Characterization:
  input_datasets:
    - name: UCLA-LDCT
  metrics:
    voxel:
      - all # Availabel param: histogram, skewness, kurtosis, snr, kde
    metadata:
      - all # Availabel options: slice_thickness, manufacturer, convolution_kernel
  params:
    clip_range : [-1024, 3071] # Standard HU range
    bins: 64
    kde_points: 1000 
    kde_sample: 100000 # If not specfied, uses all voxel values to compute kde; can be computationally expensive

Harmonization:
  mode: "test"
  input_datasets:
    - name: NLST
      in_uids: "./utils_tmp/csvs/totest_order.csv"
    # - name: NLST-2
    #   in_uids: "./utils_tmp/csvs/totest_order.csv"
  models:
    - name: SNGAN
      pretrained_G: "./pretrained_weights/SNGAN/latestG-1-1.pth"
    - name: WGAN
      pretrained_G: "./pretrained_weights/WGAN/latestG-1-1.pth"
  param:
    tile_xy: 512
    tile_z: 32
    z_overlap: 4
    gpu_id: 0
    out_dtype: ".nii.gz"
  metrics:
    - sobel
    - radiomic

Robustness:
  input_datasets:
    - name: NLST
      in_uids: "./utils_tmp/csvs/nlst_input.csv"
      variability:
        - manufacturer
        - slice_thickness
      load_from: "20250204-142207-4f"

  param:
    model_type: "sybil_ensemble"
    evaluate: false

