Global:
  session_base_path: "./SESSIONS"

Datasets:
  NLST:
    in_uids: "/path_to_nlst_cases.csv"
    in_dtype: ".dcm"
    description: "National Lung Screening Trial dataset"

Modules:
  Characterization: true
  Harmonization: true
  Robustness: true

Characterization:
  input_datasets:
    - name: NLST
  metrics:
    voxel:
      - all
    metadata:
      - all
  params:
    clip_range : [-1024, 3071] # Standard HU range
    bins: 64
    kde_points: 1e3
    kde_sample: 1e5

Harmonization:
  mode: "test"
  input_datasets:
    - name: NLST
    - in_uids: "/path_to_nlst_subset_data.csv"
  models:
    - name: SNGAN
      pretrained_G: "./pretrained_weights/SNGAN/latestG-1-1.pth"
  param:
    tile_xy: 512
    tile_z: 32
    z_overlap: 4
    gpu_id: 0
    out_dtype: ".nii.gz"
    save_lr: true
  metrics:
    - snr
    - sobel
    - radiomic

Robustness:
  input_datasets:
    - name: NLST
      variability:
        - manufacturer
        - slice_thickness
        - convolution_kernel
      in_uids: "/path_to_nlst_subset_data.csv"

  param:
    model_type: "sybil_ensemble"
    evaluate: true
