Global:
  session_base_path: "./SESSIONS"  # Base path where all session folders will be created

Datasets:
  NLST:
    in_uids: "/workspace/ctnorm/utils/csvs/nlst2mm_subset.csv" # "/data/uids/cv_uids/ucla_test_uids_fold_3_merged-tmp.txt"
    in_dtype: "dcm"
    description: "National Lung Screening Trial dataset"

Modules:
  Characterization: true
  Harmonization: true
  Robustness: true

Characterization:
  input_datasets:
    - name: NLST

Harmonization:
  mode: "test"
  input_datasets:
    - name: NLST
  models:
    - name: SNGAN
      pretrained_G: "./pretrained_weights/SNGAN/latestG-1-1.pth"
  param:
    tile_xy: 512
    tile_z: 32
    z_overlap: 4
    gpu_id: 0
    out_dtype: "dcm"

Robustness:
  input_datasets:
    - name: NLST
      in_uids: "./utils/csvs/nlst2mm_subset_with_label.csv"
      variability:
        name: "manufacturer" # convolution_kernel, slice_thickness
        # load_from: "20250203-033504-40"
  param:
    model_type: "sybil_ensemble" # sybil_1, sybil_2, sybil_3, sybil_4, sybil_5 and sybil_ensemble
    evaluate: false # label and time_to_event column needed for evaluation