Global:
  session_base_path: "./SESSIONS"

Datasets:
  NLST:
    in_uids: "./utils_tmp/csvs/totest_order.csv"
    in_dtype: "dcm"
    description: "National Lung Screening Trial dataset"
  NLST-2:
    in_uids: "./utils_tmp/csvs/totest_order.csv"
    in_dtype: "dcm"
    description: "National Lung Screening Trial dataset again"

Modules:
  Characterization: false
  Harmonization: true
  Robustness: false

Characterization:
  input_datasets:
    - name: NLST

Harmonization:
  mode: "test"
  input_datasets:
    - name: NLST
    - name: NLST-2
  models:
    - name: SNGAN
      pretrained_G: "./pretrained_weights/SNGAN/latestG-1-1.pth"
  param:
    tile_xy: 512
    tile_z: 32
    z_overlap: 4
    gpu_id: 0
    out_dtype: ".nii.gz"
  metrics:
    - Radiomic

Robustness:
  input_datasets:
    - name: NLST
      # in_uids: "path_to_nlst_subset.csv"
      variability:
        name: "manufacturer"
        name: "slice_thickness" 
  param:
    model_type: "sybil_ensemble"
    evaluate: false

