Global:
  session_base_path: "./SESSIONS"  # Base path where all session folders will be created


Datasets:
  NLST:
    uids: "/workspace/ctnorm/utils/csvs/nlst2mm_subset.csv" # "/data/uids/cv_uids/ucla_test_uids_fold_3_merged-tmp.txt"
    in_dtype: "dcm" # "h5"
    description: "National Lung Screening Trial dataset"
  CustomDataset:
    input_path: "path/to/custom"
    description: "Custom dataset for validation"

 
Modules:
  Characterization: false
  Harmonization: true
  Robustness: false


Harmonization:
  mode: "test"
  input_datasets:
    - name: NLST
  models:
    SNGAN: "./Harmonization/pretrained_weights/SNGAN/latestG-1-1.pth"
    # RRDB: "./Harmonization/pretrained_weights/RRDB/latestG-1-1.pth"
  param:
    tile_xy: 512
    tile_z: 32
    z_overlap: 4
    gpu_id: 1
    out_dtype: "dcm"
  metrics:
    - sobel
    - tsne